// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSX5wZ33O_lm6O6Hu7hoohZfWsRkwvwgw',
    appId: '1:265565038727:web:abee993d30580702e7f022',
    messagingSenderId: '265565038727',
    projectId: 'checkpoint-ia',
    authDomain: 'checkpoint-ia.firebaseapp.com',
    storageBucket: 'checkpoint-ia.firebasestorage.app',
    measurementId: 'G-CJ3K56BE44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFDb7FxOl3pdKs2_YIb15bF0lvqvmO7s',
    appId: '1:265565038727:android:ce56167e875d4f62e7f022',
    messagingSenderId: '265565038727',
    projectId: 'checkpoint-ia',
    storageBucket: 'checkpoint-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTqCREbOLefJr-0GseEZE4Vy8y9W6Ryc',
    appId: '1:265565038727:ios:f50df7c6d0b50ab7e7f022',
    messagingSenderId: '265565038727',
    projectId: 'checkpoint-ia',
    storageBucket: 'checkpoint-ia.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTqCREbOLefJr-0GseEZE4Vy8y9W6Ryc',
    appId: '1:265565038727:ios:f50df7c6d0b50ab7e7f022',
    messagingSenderId: '265565038727',
    projectId: 'checkpoint-ia',
    storageBucket: 'checkpoint-ia.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSX5wZ33O_lm6O6Hu7hoohZfWsRkwvwgw',
    appId: '1:265565038727:web:61e6d0ebfef0e174e7f022',
    messagingSenderId: '265565038727',
    projectId: 'checkpoint-ia',
    authDomain: 'checkpoint-ia.firebaseapp.com',
    storageBucket: 'checkpoint-ia.firebasestorage.app',
    measurementId: 'G-CYXDS6S6MJ',
  );
}
